### ISSUE TITLE
大佬, 借用下你的代码

### ISSUE THREAD

**Issue by xhawk18** [LeeReindeer/ROS#1]
ROS代码写的很优秀！

[s_task](https://github.com/xhawk18/s_task) 是一个支持各种平台的协程多任务库，
avr分支借用了大佬写的协程切换和时钟初始化代码 :sweat_smile:，
今天已经集成进去一点了。

过来特别表示下感谢！

**Comment by LeeReindeer** [comment]
谢谢，很高兴能帮到你！

**Comment by LeeReindeer** [comment]
avr的移植我有参考过这个 https://github.com/kelvinlawson/atomthreads/tree/master/ports/avr

**Comment by xhawk18** [comment]
> avr的移植我有参考过这个 https://github.com/kelvinlawson/atomthreads/tree/master/ports/avr

谢谢，也参考下
